language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
  - 6
  - iojs
services:
  - mongodb
branches:
  only:
    - master
before_install:
  - "npm install -g istanbul"
script:
  - "npm run test-ci"
after_script:
  - "npm install -g coveralls"
  - "cat ./coverage/lcov.info | coveralls"